const KEY='wcc_v1_online_control';
const defaults={decision:'FIX',priority:'High',blocker:'Frontend design fidelity and development control need stronger structure before continuing Executive Engine feature work.',nextAction:'Use WCC V1 online to control builds, tests, decisions, prompts, and deployment reports in real time.',links:[['Frontend live','https://executive-engine-frontend.onrender.com/'],['Backend root','https://executive-engine-os.onrender.com/'],['Backend /health','https://executive-engine-os.onrender.com/health'],['Backend /debug','https://executive-engine-os.onrender.com/debug'],['Backend /test-report-json','https://executive-engine-os.onrender.com/test-report-json']],tests:[{name:'Backend /health',status:'PASS',note:'V37700 stable'},{name:'Frontend live',status:'FAIL',note:'Design/function control needs WCC tracking'}],uploads:[],queue:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
const $=id=>document.getElementById(id); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function syncFromFields(){state.decision=$('decision').value;state.priority=$('priority').value;state.blocker=$('blocker').value;state.nextAction=$('nextAction').value;save();render();}
['decision','priority','blocker','nextAction'].forEach(id=>setTimeout(()=>$(id).addEventListener('input',syncFromFields),0));
function initFields(){ $('decision').value=state.decision;$('priority').value=state.priority;$('blocker').value=state.blocker;$('nextAction').value=state.nextAction; }
function addReply(){const text=$('replyText').value.trim(); if(!text)return; state.queue.unshift({source:$('replySource').value||'System',status:$('replyStatus').value,text,time:new Date().toLocaleString()}); $('replyText').value=''; save();render();}
function addLink(){if(!$('linkName').value||!$('linkUrl').value)return; state.links.push([$('linkName').value,$('linkUrl').value]); $('linkName').value='';$('linkUrl').value=''; save();render();}
function addTest(){if(!$('testName').value)return; state.tests.push({name:$('testName').value,status:$('testStatus').value,note:$('testNote').value}); $('testName').value='';$('testNote').value=''; save();render();}
function addUpload(){if(!$('uploadName').value)return; state.uploads.unshift({filename:$('uploadName').value,type:$('uploadType').value,note:$('uploadNote').value,time:new Date().toLocaleString()}); $('uploadName').value='';$('uploadNote').value=''; save();render();}
function del(type,i){state[type].splice(i,1);save();render();}
function counts(){return{Unread:state.queue.filter(x=>x.status==='Unread').length,Action:state.queue.filter(x=>x.status==='Action Needed').length,Waiting:state.queue.filter(x=>x.status==='Waiting').length,Reviewed:state.queue.filter(x=>x.status==='Reviewed').length}}
function report(){return `WILL WEBB COMMAND CENTRE REPORT\n\nDECISION:\n${state.decision}\n\nPRIORITY:\n${state.priority}\n\nCURRENT BLOCKER:\n${state.blocker}\n\nNEXT EXACT ACTION:\n${state.nextAction}\n\nSYSTEM REPLIES / CHAT RESPONSES:\n${state.queue.length?state.queue.map(q=>`- ${q.source}: ${q.status} — ${q.text} (${q.time})`).join('\n'):'- None logged.'}\n\nTEST RESULTS:\n${state.tests.map(t=>`- ${t.name}: ${t.status} — ${t.note||''}`).join('\n')}\n\nTEST LINKS:\n${state.links.map(l=>`- ${l[0]}: ${l[1]}`).join('\n')}\n\nRECENT UPLOADS:\n${state.uploads.length?state.uploads.map(u=>`- ${u.filename} (${u.type}) — ${u.note||''}`).join('\n'):'- None logged.'}\n\nASK:\nReview the queued system replies and tell me the exact next action. Do not redesign unless approved. Do not touch backend unless required. Give HOLD / FIX / PROMOTE / ROLLBACK.`}
function prompt(type){if(type==='frontend')return `FRONTEND FIX ONLY.\n\nCURRENT DECISION: ${state.decision}\nPRIORITY: ${state.priority}\nBLOCKER: ${state.blocker}\nNEXT ACTION: ${state.nextAction}\n\nDO NOT TOUCH BACKEND, SUPABASE, API URL, OR RENDER SETTINGS.\nReturn frontend-only ZIP with README, checklist, validation.`; if(type==='deploy')return `DEPLOYMENT TESTING.\n\nVerify live frontend, backend health/debug/test-report, version badge, command execution, response render, summary/category rail. Return HOLD/FIX/PROMOTE.`; if(type==='queue')return report(); return `ROLLBACK PLAN. Restore last stable visual/functioning version. Preserve backend. Identify exact files/version to restore.`}
async function copy(txt){await navigator.clipboard.writeText(txt);}
function render(){const c=counts();$('mUnread').textContent=c.Unread;$('mAction').textContent=c.Action;$('mWaiting').textContent=c.Waiting;$('mReviewed').textContent=c.Reviewed;$('queue').innerHTML=state.queue.map((q,i)=>`<div class='reply'><span class='badge ${q.status.split(' ')[0]}'>${q.status}</span><strong>${q.source}</strong><p>${q.text}</p><small>${q.time}</small><br><button onclick="del('queue',${i})">x</button></div>`).join('')||'<p>No replies logged.</p>';$('linksList').innerHTML=state.links.map((l,i)=>`<div class='link'><strong>${l[0]}</strong><br><a href='${l[1]}' target='_blank'>${l[1]}</a> <button onclick="del('links',${i})">x</button></div>`).join('');$('testsBody').innerHTML=state.tests.map((t,i)=>`<tr><td>${t.name}</td><td class='${t.status}'>${t.status}</td><td>${t.note||''}</td><td><button onclick="del('tests',${i})">x</button></td></tr>`).join('');$('uploadsList').innerHTML=state.uploads.map((u,i)=>`<div class='upload'><strong>${u.filename}</strong><span class='badge'>${u.type}</span><p>${u.note||''}</p><small>${u.time}</small><br><button onclick="del('uploads',${i})">x</button></div>`).join('')||'<p>No uploads logged.</p>';$('report').textContent=report();}
$('addReply').onclick=addReply;$('addLink').onclick=addLink;$('addTest').onclick=addTest;$('addUpload').onclick=addUpload;$('copyBtn').onclick=()=>copy(report());$('copyFull').onclick=()=>copy(report());$('saveBtn').onclick=syncFromFields;$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='wcc-v1-export.json';a.click()};$('resetBtn').onclick=()=>{if(confirm('Reset WCC V1 local data?')){localStorage.removeItem(KEY);location.reload()}};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>copy(prompt(b.dataset.prompt)));
window.addEventListener('storage',e=>{if(e.key===KEY){state=JSON.parse(e.newValue)||state;initFields();render();}});
setInterval(()=>{const latest=localStorage.getItem(KEY); if(latest){const n=JSON.parse(latest); if(JSON.stringify(n)!==JSON.stringify(state)){state=n;initFields();render();}}},1000);
initFields();render();